/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const WithdrawalId = IDL.Nat;
export const PaymentId = IDL.Nat;
export const TxId = IDL.Nat;
export const Transaction = IDL.Record({
  'status' : IDL.Text,
  'userId' : UserId,
  'note' : IDL.Text,
  'txId' : TxId,
  'level' : IDL.Opt(IDL.Nat),
  'fromUserId' : IDL.Opt(UserId),
  'timestamp' : IDL.Int,
  'txType' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserType = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const Mobile = IDL.Text;
export const User = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'referralCode' : IDL.Text,
  'joinDate' : IDL.Int,
  'userId' : UserId,
  'name' : IDL.Text,
  'role' : UserType,
  'sponsorId' : IDL.Opt(UserId),
  'rightChildId' : IDL.Opt(UserId),
  'leftChildId' : IDL.Opt(UserId),
  'isActive' : IDL.Bool,
  'mobile' : Mobile,
  'walletBalance' : IDL.Float64,
});
export const WithdrawalRequest = IDL.Record({
  'status' : IDL.Text,
  'ifscCode' : IDL.Text,
  'userId' : UserId,
  'bankName' : IDL.Text,
  'adminNote' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
  'processedDate' : IDL.Opt(IDL.Int),
  'amount' : IDL.Float64,
  'requestDate' : IDL.Int,
  'reqId' : WithdrawalId,
});
export const ProductId = IDL.Nat;
export const PaymentRecord = IDL.Record({
  'status' : IDL.Text,
  'userId' : UserId,
  'productId' : ProductId,
  'adminNote' : IDL.Text,
  'paymentId' : PaymentId,
  'timestamp' : IDL.Int,
  'upiTransactionRef' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'userId' : UserId,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'mobile' : Mobile,
  'walletBalance' : IDL.Float64,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productId' : ProductId,
  'isActive' : IDL.Bool,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAddUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserId],
      [],
    ),
  'adminApproveWithdrawal' : IDL.Func([WithdrawalId, IDL.Text], [], []),
  'adminConfirmPayment' : IDL.Func([PaymentId], [], []),
  'adminCreateProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'adminCreditIncome' : IDL.Func([UserId, IDL.Float64, IDL.Text], [], []),
  'adminGetAllTransactions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(User)], ['query']),
  'adminGetAllWithdrawals' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'adminGetDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeUsers' : IDL.Nat,
          'totalIncomeDistributed' : IDL.Float64,
          'totalPayments' : IDL.Nat,
          'pendingWithdrawalsCount' : IDL.Nat,
          'pendingWithdrawalsAmount' : IDL.Float64,
          'totalUsers' : IDL.Nat,
          'pendingPaymentsCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'adminGetPaymentHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'adminGetPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'adminGetPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'adminRejectPayment' : IDL.Func([PaymentId, IDL.Text], [], []),
  'adminRejectWithdrawal' : IDL.Func([WithdrawalId, IDL.Text], [], []),
  'adminSetBinaryPosition' : IDL.Func(
      [UserId, UserId, IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null })],
      [],
      [],
    ),
  'adminToggleProduct' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
  'getTransactions' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserById' : IDL.Func([UserId], [User], ['query']),
  'getUserByMobile' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserByReferralCode' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserPayments' : IDL.Func([UserId], [IDL.Vec(PaymentRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'balance' : IDL.Float64,
          'transactions' : IDL.Vec(Transaction),
        }),
      ],
      ['query'],
    ),
  'getWithdrawalRequests' : IDL.Func(
      [UserId],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'loginUserByMobile' : IDL.Func([IDL.Text], [User], []),
  'purchaseProduct' : IDL.Func([UserId, ProductId], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [User],
      [],
    ),
  'requestWithdrawal' : IDL.Func(
      [UserId, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPaymentRequest' : IDL.Func(
      [UserId, ProductId, IDL.Text],
      [PaymentId],
      [],
    ),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const WithdrawalId = IDL.Nat;
  const PaymentId = IDL.Nat;
  const TxId = IDL.Nat;
  const Transaction = IDL.Record({
    'status' : IDL.Text,
    'userId' : UserId,
    'note' : IDL.Text,
    'txId' : TxId,
    'level' : IDL.Opt(IDL.Nat),
    'fromUserId' : IDL.Opt(UserId),
    'timestamp' : IDL.Int,
    'txType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserType = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const Mobile = IDL.Text;
  const User = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'referralCode' : IDL.Text,
    'joinDate' : IDL.Int,
    'userId' : UserId,
    'name' : IDL.Text,
    'role' : UserType,
    'sponsorId' : IDL.Opt(UserId),
    'rightChildId' : IDL.Opt(UserId),
    'leftChildId' : IDL.Opt(UserId),
    'isActive' : IDL.Bool,
    'mobile' : Mobile,
    'walletBalance' : IDL.Float64,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : IDL.Text,
    'ifscCode' : IDL.Text,
    'userId' : UserId,
    'bankName' : IDL.Text,
    'adminNote' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
    'processedDate' : IDL.Opt(IDL.Int),
    'amount' : IDL.Float64,
    'requestDate' : IDL.Int,
    'reqId' : WithdrawalId,
  });
  const ProductId = IDL.Nat;
  const PaymentRecord = IDL.Record({
    'status' : IDL.Text,
    'userId' : UserId,
    'productId' : ProductId,
    'adminNote' : IDL.Text,
    'paymentId' : PaymentId,
    'timestamp' : IDL.Int,
    'upiTransactionRef' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'userId' : UserId,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'mobile' : Mobile,
    'walletBalance' : IDL.Float64,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productId' : ProductId,
    'isActive' : IDL.Bool,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAddUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserId],
        [],
      ),
    'adminApproveWithdrawal' : IDL.Func([WithdrawalId, IDL.Text], [], []),
    'adminConfirmPayment' : IDL.Func([PaymentId], [], []),
    'adminCreateProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'adminCreditIncome' : IDL.Func([UserId, IDL.Float64, IDL.Text], [], []),
    'adminGetAllTransactions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(User)],
        ['query'],
      ),
    'adminGetAllWithdrawals' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'adminGetDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeUsers' : IDL.Nat,
            'totalIncomeDistributed' : IDL.Float64,
            'totalPayments' : IDL.Nat,
            'pendingWithdrawalsCount' : IDL.Nat,
            'pendingWithdrawalsAmount' : IDL.Float64,
            'totalUsers' : IDL.Nat,
            'pendingPaymentsCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'adminGetPaymentHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'adminGetPendingPayments' : IDL.Func(
        [],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'adminGetPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'adminRejectPayment' : IDL.Func([PaymentId, IDL.Text], [], []),
    'adminRejectWithdrawal' : IDL.Func([WithdrawalId, IDL.Text], [], []),
    'adminSetBinaryPosition' : IDL.Func(
        [
          UserId,
          UserId,
          IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
        ],
        [],
        [],
      ),
    'adminToggleProduct' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
    'getTransactions' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserById' : IDL.Func([UserId], [User], ['query']),
    'getUserByMobile' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserByReferralCode' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserPayments' : IDL.Func([UserId], [IDL.Vec(PaymentRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'balance' : IDL.Float64,
            'transactions' : IDL.Vec(Transaction),
          }),
        ],
        ['query'],
      ),
    'getWithdrawalRequests' : IDL.Func(
        [UserId],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'loginUserByMobile' : IDL.Func([IDL.Text], [User], []),
    'purchaseProduct' : IDL.Func([UserId, ProductId], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [User],
        [],
      ),
    'requestWithdrawal' : IDL.Func(
        [UserId, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPaymentRequest' : IDL.Func(
        [UserId, ProductId, IDL.Text],
        [PaymentId],
        [],
      ),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };