/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Mobile = string;
export type OTP = string;
export interface Product {
  'name' : string,
  'description' : string,
  'productId' : ProductId,
  'isActive' : boolean,
  'price' : number,
}
export type ProductId = bigint;
export interface Transaction {
  'status' : string,
  'userId' : UserId,
  'note' : string,
  'txId' : TxId,
  'level' : [] | [bigint],
  'fromUserId' : [] | [UserId],
  'timestamp' : bigint,
  'txType' : string,
  'amount' : number,
}
export type TxId = bigint;
export interface User {
  'principal' : [] | [Principal],
  'referralCode' : string,
  'joinDate' : bigint,
  'userId' : UserId,
  'name' : string,
  'role' : UserRole,
  'sponsorId' : [] | [UserId],
  'rightChildId' : [] | [UserId],
  'leftChildId' : [] | [UserId],
  'isActive' : boolean,
  'mobile' : Mobile,
  'walletBalance' : number,
}
export type UserId = bigint;
export interface UserProfile {
  'referralCode' : string,
  'userId' : UserId,
  'name' : string,
  'isActive' : boolean,
  'mobile' : Mobile,
  'walletBalance' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WithdrawalId = bigint;
export interface WithdrawalRequest {
  'status' : string,
  'ifscCode' : string,
  'userId' : UserId,
  'bankName' : string,
  'adminNote' : string,
  'upiId' : string,
  'accountNumber' : string,
  'processedDate' : [] | [bigint],
  'amount' : number,
  'requestDate' : bigint,
  'reqId' : WithdrawalId,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAddUser' : ActorMethod<[string, string, string, string], UserId>,
  'adminApproveWithdrawal' : ActorMethod<[WithdrawalId, string], undefined>,
  'adminCreateProduct' : ActorMethod<[string, string, number], undefined>,
  'adminCreditIncome' : ActorMethod<[UserId, number, string], undefined>,
  'adminGetAllTransactions' : ActorMethod<[bigint, bigint], Array<Transaction>>,
  'adminGetAllUsers' : ActorMethod<[bigint, bigint], Array<User>>,
  'adminGetAllWithdrawals' : ActorMethod<
    [bigint, bigint],
    Array<WithdrawalRequest>
  >,
  'adminGetDashboardStats' : ActorMethod<
    [],
    {
      'activeUsers' : bigint,
      'totalIncomeDistributed' : number,
      'pendingWithdrawalsCount' : bigint,
      'pendingWithdrawalsAmount' : number,
      'totalUsers' : bigint,
    }
  >,
  'adminGetPendingWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'adminRejectWithdrawal' : ActorMethod<[WithdrawalId, string], undefined>,
  'adminSetBinaryPosition' : ActorMethod<
    [UserId, UserId, { 'left' : null } | { 'right' : null }],
    undefined
  >,
  'adminToggleProduct' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'generateOTP' : ActorMethod<[string], OTP>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getTransactions' : ActorMethod<[UserId, bigint, bigint], Array<Transaction>>,
  'getUserById' : ActorMethod<[UserId], User>,
  'getUserByMobile' : ActorMethod<[Mobile], User>,
  'getUserByReferralCode' : ActorMethod<[string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<
    [UserId],
    { 'balance' : number, 'transactions' : Array<Transaction> }
  >,
  'getWithdrawalRequests' : ActorMethod<[UserId], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, OTP], User>,
  'purchaseProduct' : ActorMethod<[UserId, ProductId], undefined>,
  'registerUser' : ActorMethod<[string, string, string, string, OTP], User>,
  'requestWithdrawal' : ActorMethod<
    [UserId, number, string, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyOTP' : ActorMethod<[string, OTP], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];