/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Mobile = string;
export interface User {
    principal?: Principal;
    referralCode: string;
    joinDate: bigint;
    userId: UserId;
    name: string;
    role: UserType;
    sponsorId?: UserId;
    rightChildId?: UserId;
    leftChildId?: UserId;
    isActive: boolean;
    mobile: Mobile;
    walletBalance: number;
}
export type TxId = bigint;
export interface PaymentRecord {
    status: string;
    userId: UserId;
    productId: ProductId;
    adminNote: string;
    paymentId: PaymentId;
    timestamp: bigint;
    upiTransactionRef: string;
    amount: number;
}
export type WithdrawalId = bigint;
export interface Transaction {
    status: string;
    userId: UserId;
    note: string;
    txId: TxId;
    level?: bigint;
    fromUserId?: UserId;
    timestamp: bigint;
    txType: string;
    amount: number;
}
export type UserId = bigint;
export type PaymentId = bigint;
export type ProductId = bigint;
export interface WithdrawalRequest {
    status: string;
    ifscCode: string;
    userId: UserId;
    bankName: string;
    adminNote: string;
    upiId: string;
    accountNumber: string;
    processedDate?: bigint;
    amount: number;
    requestDate: bigint;
    reqId: WithdrawalId;
}
export interface Product {
    name: string;
    description: string;
    productId: ProductId;
    isActive: boolean;
    price: number;
}
export interface UserProfile {
    referralCode: string;
    userId: UserId;
    name: string;
    isActive: boolean;
    mobile: Mobile;
    walletBalance: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    admin = "admin",
    user = "user"
}
export enum Variant_left_right {
    left = "left",
    right = "right"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminAddUser(name: string, mobile: string, referralCode: string, sponsorReferralCode: string): Promise<UserId>;
    adminApproveWithdrawal(reqId: WithdrawalId, adminNote: string): Promise<void>;
    adminConfirmPayment(paymentId: PaymentId): Promise<void>;
    adminCreateProduct(name: string, description: string, price: number): Promise<void>;
    adminCreditIncome(userId: UserId, amount: number, note: string): Promise<void>;
    adminGetAllTransactions(limit: bigint, offset: bigint): Promise<Array<Transaction>>;
    adminGetAllUsers(limit: bigint, offset: bigint): Promise<Array<User>>;
    adminGetAllWithdrawals(limit: bigint, offset: bigint): Promise<Array<WithdrawalRequest>>;
    adminGetDashboardStats(): Promise<{
        activeUsers: bigint;
        totalIncomeDistributed: number;
        totalPayments: bigint;
        pendingWithdrawalsCount: bigint;
        pendingWithdrawalsAmount: number;
        totalUsers: bigint;
        pendingPaymentsCount: bigint;
    }>;
    adminGetPaymentHistory(limit: bigint, offset: bigint): Promise<Array<PaymentRecord>>;
    adminGetPendingPayments(): Promise<Array<PaymentRecord>>;
    adminGetPendingWithdrawals(): Promise<Array<WithdrawalRequest>>;
    adminRejectPayment(paymentId: PaymentId, note: string): Promise<void>;
    adminRejectWithdrawal(reqId: WithdrawalId, adminNote: string): Promise<void>;
    adminSetBinaryPosition(parentUserId: UserId, childUserId: UserId, position: Variant_left_right): Promise<void>;
    adminToggleProduct(productId: ProductId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    generateOTP(mobile: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProducts(): Promise<Array<Product>>;
    getTransactions(userId: UserId, limit: bigint, offset: bigint): Promise<Array<Transaction>>;
    getUserById(userId: UserId): Promise<User>;
    getUserByMobile(mobile: string): Promise<User>;
    getUserByReferralCode(code: string): Promise<User>;
    getUserPayments(userId: UserId): Promise<Array<PaymentRecord>>;
    getUserProfile(userPrincipal: Principal): Promise<UserProfile | null>;
    getWallet(userId: bigint): Promise<{
        balance: number;
        transactions: Array<Transaction>;
    }>;
    getWithdrawalRequests(userId: UserId): Promise<Array<WithdrawalRequest>>;
    isCallerAdmin(): Promise<boolean>;
    loginUserByMobile(mobile: string): Promise<User>;
    purchaseProduct(userId: UserId, productId: ProductId): Promise<void>;
    registerUser(fullName: string, mobileNumber: string, sponsorCode: string): Promise<User>;
    requestWithdrawal(userId: UserId, amount: number, bankName: string, accountNumber: string, ifscCode: string, upiId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPaymentRequest(userId: UserId, productId: ProductId, upiTransactionRef: string): Promise<PaymentId>;
}
import type { Mobile as _Mobile, Transaction as _Transaction, TxId as _TxId, User as _User, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType, WithdrawalId as _WithdrawalId, WithdrawalRequest as _WithdrawalRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminAddUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<UserId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminApproveWithdrawal(arg0: WithdrawalId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveWithdrawal(arg0, arg1);
            return result;
        }
    }
    async adminConfirmPayment(arg0: PaymentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminConfirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminConfirmPayment(arg0);
            return result;
        }
    }
    async adminCreateProduct(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateProduct(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateProduct(arg0, arg1, arg2);
            return result;
        }
    }
    async adminCreditIncome(arg0: UserId, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreditIncome(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreditIncome(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGetAllTransactions(arg0: bigint, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUsers(arg0: bigint, arg1: bigint): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers(arg0, arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers(arg0, arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllWithdrawals(arg0: bigint, arg1: bigint): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllWithdrawals(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllWithdrawals(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetDashboardStats(): Promise<{
        activeUsers: bigint;
        totalIncomeDistributed: number;
        totalPayments: bigint;
        pendingWithdrawalsCount: bigint;
        pendingWithdrawalsAmount: number;
        totalUsers: bigint;
        pendingPaymentsCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardStats();
            return result;
        }
    }
    async adminGetPaymentHistory(arg0: bigint, arg1: bigint): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPaymentHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPaymentHistory(arg0, arg1);
            return result;
        }
    }
    async adminGetPendingPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingPayments();
            return result;
        }
    }
    async adminGetPendingWithdrawals(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectPayment(arg0: PaymentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectPayment(arg0, arg1);
            return result;
        }
    }
    async adminRejectWithdrawal(arg0: WithdrawalId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectWithdrawal(arg0, arg1);
            return result;
        }
    }
    async adminSetBinaryPosition(arg0: UserId, arg1: UserId, arg2: Variant_left_right): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetBinaryPosition(arg0, arg1, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetBinaryPosition(arg0, arg1, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminToggleProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminToggleProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminToggleProduct(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateOTP(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOTP(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getTransactions(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0, arg1, arg2);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0, arg1, arg2);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: UserId): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByMobile(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByMobile(arg0);
                return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByMobile(arg0);
            return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByReferralCode(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByReferralCode(arg0);
                return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByReferralCode(arg0);
            return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPayments(arg0: UserId): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPayments(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(arg0: bigint): Promise<{
        balance: number;
        transactions: Array<Transaction>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet(arg0);
                return from_candid_record_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet(arg0);
            return from_candid_record_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequests(arg0: UserId): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginUserByMobile(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUserByMobile(arg0);
                return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUserByMobile(arg0);
            return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseProduct(arg0: UserId, arg1: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseProduct(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: UserId, arg1: number, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPaymentRequest(arg0: UserId, arg1: ProductId, arg2: string): Promise<PaymentId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentRequest(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Transaction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_User_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    ifscCode: string;
    userId: _UserId;
    bankName: string;
    adminNote: string;
    upiId: string;
    accountNumber: string;
    processedDate: [] | [bigint];
    amount: number;
    requestDate: bigint;
    reqId: _WithdrawalId;
}): {
    status: string;
    ifscCode: string;
    userId: UserId;
    bankName: string;
    adminNote: string;
    upiId: string;
    accountNumber: string;
    processedDate?: bigint;
    amount: number;
    requestDate: bigint;
    reqId: WithdrawalId;
} {
    return {
        status: value.status,
        ifscCode: value.ifscCode,
        userId: value.userId,
        bankName: value.bankName,
        adminNote: value.adminNote,
        upiId: value.upiId,
        accountNumber: value.accountNumber,
        processedDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.processedDate)),
        amount: value.amount,
        requestDate: value.requestDate,
        reqId: value.reqId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    transactions: Array<_Transaction>;
}): {
    balance: number;
    transactions: Array<Transaction>;
} {
    return {
        balance: value.balance,
        transactions: from_candid_vec_n1(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    userId: _UserId;
    note: string;
    txId: _TxId;
    level: [] | [bigint];
    fromUserId: [] | [_UserId];
    timestamp: bigint;
    txType: string;
    amount: number;
}): {
    status: string;
    userId: UserId;
    note: string;
    txId: TxId;
    level?: bigint;
    fromUserId?: UserId;
    timestamp: bigint;
    txType: string;
    amount: number;
} {
    return {
        status: value.status,
        userId: value.userId,
        note: value.note,
        txId: value.txId,
        level: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.level)),
        fromUserId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.fromUserId)),
        timestamp: value.timestamp,
        txType: value.txType,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: [] | [Principal];
    referralCode: string;
    joinDate: bigint;
    userId: _UserId;
    name: string;
    role: _UserType;
    sponsorId: [] | [_UserId];
    rightChildId: [] | [_UserId];
    leftChildId: [] | [_UserId];
    isActive: boolean;
    mobile: _Mobile;
    walletBalance: number;
}): {
    principal?: Principal;
    referralCode: string;
    joinDate: bigint;
    userId: UserId;
    name: string;
    role: UserType;
    sponsorId?: UserId;
    rightChildId?: UserId;
    leftChildId?: UserId;
    isActive: boolean;
    mobile: Mobile;
    walletBalance: number;
} {
    return {
        principal: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.principal)),
        referralCode: value.referralCode,
        joinDate: value.joinDate,
        userId: value.userId,
        name: value.name,
        role: from_candid_UserType_n10(_uploadFile, _downloadFile, value.role),
        sponsorId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sponsorId)),
        rightChildId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.rightChildId)),
        leftChildId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.leftChildId)),
        isActive: value.isActive,
        mobile: value.mobile,
        walletBalance: value.walletBalance
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserType {
    return "admin" in value ? UserType.admin : "user" in value ? UserType.user : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_left_right): {
    left: null;
} | {
    right: null;
} {
    return value == Variant_left_right.left ? {
        left: null
    } : value == Variant_left_right.right ? {
        right: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
